#配置示例文件
[configs.test]
ssh_username = "root"
ssh_password = "Hj@123456"
server_address = "47.121.197.204:22"
file_path = "D:/0-work/0-zqcm/docs/中起项目.pdf"
upload_path = "/home/zqcm/docs/"

[configs.prod]
ssh_username = "root"
ssh_private_key_path = "D:/0-work/0-zqcm/zqcm.pem"
server_address = "47.121.197.204:22"
local_pre_upload_script = "D:/0-work/0-zqcm/atb/test.cmd"
local_post_upload_script = "echo 上传完成"
remote_pre_upload_script = "echo 开始下载"
remote_post_upload_script = "echo 下载完成"
file_path = "D:/0-work/0-zqcm/docs/中起项目.pdf"
upload_path = "/home/zqcm/docs/"
    